### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by Source82** [joonb14/arcface-tflite#14]
Hello,
Thanks for this good work.
Does one have to convert the dataset to tfrecord.
Or will it work by just pointing to directories.
Thanks

**Comment by joonb14** [comment]
To create TFRecord data
Follow the instructions written in https://github.com/peteryuX/arcface-tf2#data-preparing

P.S: We are refactoring our code, so it might not work right now. And also our models' accuracy is far behind the ArcFace official github. (Our Work works well on small and easy datasets like LFW, CFP-FP, and etc. But works poorly on IJB-C dataset). So I recommend you to follow the ArcFace PyTorch source code for right now (https://github.com/deepinsight/insightface/tree/master/recognition/arcface_torch)
Thank you!
